/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ConsultasITS.mx.view;

import com.ConsultasITS.mx.Pruebas_Menu.MenuPrincipalPersonal;
import com.ConsultasITS.mx.Pruebas_Menu.MenuSecundarioAdm;
import com.ConsultasITS.mx.bo.PersonaBO;
import com.ConsultasITS.mx.bo.TrabajadorBO;
import com.ConsultasITS.mx.entity.Persona;
import com.ConsultasITS.mx.entity.Trabajador;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author kevin
 */
public class FrmTrabajador_Per extends javax.swing.JFrame {

    private String nombre_Usuario=UsuarioContexto.getNombreUsuario();
    /**
     * Creates new form FrmTrabajador_Per
     */
    public FrmTrabajador_Per() {
        initComponents();
        setTitle("FORMULARIO TRABAJADOR");
        setLocationRelativeTo(null);
        setResizable(false);
        jlbMensaje.setText("USUARIO: " + nombre_Usuario);
        initComponents1();
        listarTrabajador();
        idMaxT();
        listarPersona();
        idMaxP();
         Calendar cal =  Calendar.getInstance();
         String fecha, hora;
         fecha=cal.get(Calendar.DATE)+"/"+(cal.get(Calendar.MONTH)+1)+"/"+cal.get(Calendar.YEAR);
         hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.get(cal.MINUTE);
         this.FECHA.setText(fecha);
         this.HORA.setText(hora);
         btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            txtIdTrabajador.setEditable(false);
            txtIdPersona.setEditable(false);
    }

    private PersonaBO personabo = new PersonaBO();
    public void listarPersona(){
        personabo.listarPersona(tbTrabajador);
    }
    public void idMaxP(){
        txtIdPersona.setText(personabo.getMaxID()+"");
    }
    private TrabajadorBO trabajadorbo = new TrabajadorBO();
    public void listarTrabajador(){
        trabajadorbo.listarTrabajador(tbTrabajador);
    }
    public void idMaxT(){
        txtIdTrabajador.setText(personabo.getMaxID()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGenero = new javax.swing.ButtonGroup();
        groupTipoTrabajador = new javax.swing.ButtonGroup();
        groupEstadoCivil = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdTrabajador = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        calenderFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        rdMasculino = new javax.swing.JRadioButton();
        rdFemenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rdDocente = new javax.swing.JRadioButton();
        rdAdministrativo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdsoltero = new javax.swing.JRadioButton();
        rdCasado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTrabajador = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtIdPersona = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jlbCedula = new javax.swing.JLabel();
        jlbEstado = new javax.swing.JLabel();
        jlbTipo = new javax.swing.JLabel();
        jlbGenero = new javax.swing.JLabel();
        jlbEdad = new javax.swing.JLabel();
        jlbFecha = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbMaternoo = new javax.swing.JLabel();
        jlbPaterno = new javax.swing.JLabel();
        jlbMensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbMFecha = new javax.swing.JLabel();
        FECHA = new javax.swing.JLabel();
        jlbMHora = new javax.swing.JLabel();
        HORA = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 79, 111));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Trabajador:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Materno:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Paterno:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        txtIdTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdTrabajadorKeyTyped(evt);
            }
        });

        txtPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaternoKeyTyped(evt);
            }
        });

        txtMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaternoKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Edad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Fecha Nacimiento:");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        calenderFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calenderFechaKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Genero:");

        groupGenero.add(rdMasculino);
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        rdMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdMasculinoKeyReleased(evt);
            }
        });

        groupGenero.add(rdFemenino);
        rdFemenino.setText("Femenino");
        rdFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemeninoActionPerformed(evt);
            }
        });
        rdFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdFemeninoKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tipo Trabajador:");

        groupTipoTrabajador.add(rdDocente);
        rdDocente.setText("Docente");
        rdDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDocenteActionPerformed(evt);
            }
        });

        groupTipoTrabajador.add(rdAdministrativo);
        rdAdministrativo.setText("Administrativo");
        rdAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAdministrativoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cedula:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Estado Civil:");

        groupEstadoCivil.add(rdsoltero);
        rdsoltero.setText("Soltero");
        rdsoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdsolteroActionPerformed(evt);
            }
        });

        groupEstadoCivil.add(rdCasado);
        rdCasado.setText("Casado");
        rdCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCasadoActionPerformed(evt);
            }
        });

        tbTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTrabajadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTrabajador);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBack))
                .addGap(17, 17, 17))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("ID Persona:");

        jlbCedula.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbCedula.setForeground(new java.awt.Color(204, 0, 0));

        jlbEstado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbEstado.setForeground(new java.awt.Color(204, 0, 0));

        jlbTipo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbTipo.setForeground(new java.awt.Color(204, 0, 0));

        jlbGenero.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbGenero.setForeground(new java.awt.Color(204, 0, 0));

        jlbEdad.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbEdad.setForeground(new java.awt.Color(204, 0, 0));

        jlbFecha.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbFecha.setForeground(new java.awt.Color(204, 0, 0));

        jlbNombre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbNombre.setForeground(new java.awt.Color(204, 0, 0));

        jlbMaternoo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbMaternoo.setForeground(new java.awt.Color(204, 0, 0));

        jlbPaterno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlbPaterno.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbMaternoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(calenderFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(202, 202, 202)
                                                .addComponent(jLabel11))
                                            .addComponent(jlbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jlbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rdsoltero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdCasado))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rdMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdFemenino)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jlbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jlbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdAdministrativo)))
                        .addGap(0, 73, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMaternoo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(calenderFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(jlbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdMasculino)
                    .addComponent(rdFemenino)
                    .addComponent(jLabel9)
                    .addComponent(rdDocente)
                    .addComponent(rdAdministrativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rdsoltero)
                    .addComponent(rdCasado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlbMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbMensaje.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TRABAJADOR");

        jlbMFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbMFecha.setForeground(new java.awt.Color(255, 255, 255));
        jlbMFecha.setText("FECHA:");

        FECHA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FECHA.setForeground(new java.awt.Color(255, 255, 255));
        FECHA.setText("00/00/00");

        jlbMHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbMHora.setForeground(new java.awt.Color(255, 255, 255));
        jlbMHora.setText("HORA:");

        HORA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HORA.setForeground(new java.awt.Color(255, 255, 255));
        HORA.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FECHA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbMHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HORA)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMFecha)
                            .addComponent(FECHA)
                            .addComponent(jlbMHora)
                            .addComponent(HORA))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void rdMasculinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdMasculinoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdMasculinoKeyReleased

    private void rdFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemeninoActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdFemeninoActionPerformed

    private void rdFemeninoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdFemeninoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdFemeninoKeyReleased

    private void rdDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDocenteActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdDocenteActionPerformed

    private void rdAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAdministrativoActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdAdministrativoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void rdsolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdsolteroActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdsolteroActionPerformed

    private void rdCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCasadoActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_rdCasadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(txtIdTrabajador.getText().isEmpty() || txtNombre.getText().isEmpty() || txtPaterno.getText().isEmpty()
           || txtMaterno.getText().isEmpty() || txtEdad.getText().isEmpty() || calenderFecha.getDate()==null
            || !(rdMasculino.isSelected() || rdFemenino.isSelected()) || !(rdCasado.isSelected() || rdsoltero.isSelected())
            || !(rdAdministrativo.isSelected() || rdDocente.isSelected())){
            JOptionPane.showMessageDialog(null, "LLENE LOS CAMPOS");
        }else{
            char genero, estado, tipo;
            if(rdMasculino.isSelected()){
                genero='M';
            }else{
                genero='F';
            }
            if(rdAdministrativo.isSelected()){
                tipo='A';
            }else{
                tipo='D';
            }
            if(rdsoltero.isSelected()){
                estado='S';
            }else{
                estado='C';
            }
            Date fecha_Nacimiento=calenderFecha.getDate();
            if(fecha_Nacimiento==null){
                JOptionPane.showMessageDialog(null, "Seleccione una fecha valida");
                return;
            }
            int id_Usuario=UsuarioContexto.getId_Usuario();
            Persona persona = new Persona();
            persona.setId_Persona(Integer.parseInt(txtIdPersona.getText()));
            persona.setNombre_Persona(txtNombre.getText());
            persona.setPaterno_Persona(txtPaterno.getText());
            persona.setMaterno_Persona(txtMaterno.getText());
            persona.setEdad_Persona(Integer.parseInt(txtEdad.getText()));
            persona.setFecha_nacimiento(new java.sql.Date(fecha_Nacimiento.getTime()));
            persona.setGenero_Persona((char)genero);
            persona.setId_Usuario(id_Usuario);
            Trabajador trabajador = new Trabajador();
            trabajador.setId_Trabajador(Integer.parseInt(txtIdTrabajador.getText()));
            trabajador.setTipo_Trabajador((char)tipo);
            trabajador.setCedula(txtCedula.getText());
            trabajador.setEstado_Civil((char)estado);
            trabajador.setId_Persona(Integer.parseInt(txtIdPersona.getText()));
            trabajador.setId_Usuario(id_Usuario);            
            String mensajeP=personabo.modificarPersona(persona);
            String mensajeT=trabajadorbo.modificarTrabajador(trabajador);
            if(mensajeP.contains("PERSONA ACTUALIZADA CORRECTAMENTE") && mensajeT.contains("TRABAJADOR ACTUALIZADO CORRECTAMENTE")){
                JOptionPane.showMessageDialog(null, "TRABAJADOR ACTUALIZADO CORRECTAMENTE");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR EL TRABAJADOR");
            }
            limpiar();
            listarPersona();
            
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(txtIdTrabajador.getText().isEmpty() || txtIdPersona.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "LLENE LOS CAMPOS DE ID");
        }else{
            String mensajeT=trabajadorbo.eliminarTrabajador(Integer.parseInt(txtIdTrabajador.getText()));
            String mensajeP=personabo.eliminarPersona(Integer.parseInt(txtIdTrabajador.getText()));
            if(mensajeT.contains("TRABAJADOR ELIMINADO CORRECTAMENTE") && mensajeP.contains("PERSONA ELIMINADA CORRECTAMENTE")){
                JOptionPane.showMessageDialog(null, "TRABAJADOR ELIMINADO CORRECTAMENTE");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL ELIMINAR TRABAJADOR");
            }
        }
        limpiar();
        listarPersona();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        String tipoUsuario=UsuarioContexto.getTipoUsuario();
        String nombreUsuario=UsuarioContexto.getNombreUsuario();
        if(tipoUsuario.equals("A")){
            MenuSecundarioAdm menu1 = new MenuSecundarioAdm(nombreUsuario);
            menu1.setVisible(true);
        }else if(tipoUsuario.equals("P")){
            MenuPrincipalPersonal menu = new MenuPrincipalPersonal(nombreUsuario);
            menu.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtIdTrabajador.getText().isEmpty() || txtNombre.getText().isEmpty() || txtPaterno.getText().isEmpty()
           || txtMaterno.getText().isEmpty() || txtEdad.getText().isEmpty() || calenderFecha.getDate()==null
            || !(rdMasculino.isSelected() || rdFemenino.isSelected()) || !(rdCasado.isSelected() || rdsoltero.isSelected())
            || !(rdAdministrativo.isSelected() || rdDocente.isSelected())){
            JOptionPane.showMessageDialog(null, "LLENE LOS CAMPOS");
        }else{
            char genero, estado, tipo;
            if(rdMasculino.isSelected()){
                genero='M';
            }else{
                genero='F';
            }
            if(rdAdministrativo.isSelected()){
                tipo='A';
            }else{
                tipo='D';
            }
            if(rdsoltero.isSelected()){
                estado='S';
            }else{
                estado='C';
            }
            Date fecha_Nacimiento=calenderFecha.getDate();
            if(fecha_Nacimiento==null){
                JOptionPane.showMessageDialog(null, "Seleccione una fecha valida");
                return;
            }
            int id_Usuario=UsuarioContexto.getId_Usuario();
            Persona persona = new Persona();
            persona.setId_Persona(Integer.parseInt(txtIdPersona.getText()));
            persona.setNombre_Persona(txtNombre.getText());
            persona.setPaterno_Persona(txtPaterno.getText());
            persona.setMaterno_Persona(txtMaterno.getText());
            persona.setEdad_Persona(Integer.parseInt(txtEdad.getText()));
            persona.setFecha_nacimiento(new java.sql.Date(fecha_Nacimiento.getTime()));
            persona.setGenero_Persona((char)genero);
            persona.setId_Usuario(id_Usuario);
            Trabajador trabajador = new Trabajador();
            trabajador.setId_Trabajador(Integer.parseInt(txtIdTrabajador.getText()));
            trabajador.setTipo_Trabajador((char)tipo);
            trabajador.setCedula(txtCedula.getText());
            trabajador.setEstado_Civil((char)estado);
            trabajador.setId_Persona(Integer.parseInt(txtIdPersona.getText()));
            trabajador.setId_Usuario(id_Usuario);            
            String mensajeP=personabo.agregarPersona(persona);
            String mensajeT=trabajadorbo.agregarTrabajador(trabajador);
            if(mensajeP.contains("PERSONA GUARDADA CORRECTAMENTE") && mensajeT.contains("TRABAJADOR GUARDADO CORRECTAMENTE")){
                JOptionPane.showMessageDialog(null, "TRABAJADOR GUARDADO CORRECTAMENTE");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR EL TRABAJADOR");
            }
            limpiar();
            listarPersona();
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

     public void initComponents1(){
        txtIdTrabajador.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validarYCargarTrabajador(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               validarYCargarTrabajador(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validarYCargarTrabajador(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
                calenderFecha.getDateEditor().addPropertyChangeListener("date", evt -> {
    validar();
});
    }
     public void validarYCargarTrabajador(){
         String idTexto=txtIdTrabajador.getText();
         if(!idTexto.isEmpty() && idTexto.matches("\\d+")){
             int idTrabajador=Integer.parseInt(idTexto);
             Trabajador trabajador=trabajadorbo.buscarTrabajadorPorId(idTrabajador);
             Persona persona=personabo.buscarpersonaPorId(idTrabajador);
             if(trabajador!=null){
                if(trabajador.getTipo_Trabajador()=='D'){
                    rdDocente.setSelected(true);
                }else if(trabajador.getTipo_Trabajador()=='A'){
                    rdAdministrativo.setSelected(true);
                }
                txtCedula.setText(trabajador.getCedula());
                if(trabajador.getEstado_Civil()=='S'){
                    rdsoltero.setSelected(true);
                }else if(trabajador.getEstado_Civil()=='C'){
                    rdCasado.setSelected(true);
                }
             }else{
                 rdDocente.setSelected(false);
                 rdAdministrativo.setSelected(false);
                 txtCedula.setText("");
                 rdsoltero.setSelected(false);
                 rdCasado.setSelected(false);
             }
             if(persona!=null){
                 txtNombre.setText(persona.getNombre_Persona());
                 txtPaterno.setText(persona.getPaterno_Persona());
                 txtMaterno.setText(persona.getMaterno_Persona());
                 txtEdad.setText(String.valueOf(persona.getEdad_Persona()));
                 if(persona.getGenero_Persona()=='M'){
                     rdMasculino.setSelected(true);
                 }else if(persona.getGenero_Persona()=='F'){
                     rdFemenino.setSelected(true);
                 }
                 Date fecha_Nacimiento = persona.getFecha_nacimiento();
                 calenderFecha.setDate(fecha_Nacimiento);
             }else{
                 txtNombre.setText("");
                 txtPaterno.setText("");
                 txtMaterno.setText("");
                 txtEdad.setText("");
                 rdMasculino.setSelected(false);
                 rdFemenino.setSelected(false);
                 calenderFecha.setDate(null);
             }
         }else{
                 rdDocente.setSelected(false);
                 rdAdministrativo.setSelected(false);
                 txtCedula.setText("");
                 rdsoltero.setSelected(false);
                 rdCasado.setSelected(false);
                 txtNombre.setText("");
                 txtPaterno.setText("");
                 txtMaterno.setText("");
                 txtEdad.setText("");
                 rdMasculino.setSelected(false);
                 rdFemenino.setSelected(false);
                 calenderFecha.setDate(null);
         }
         
     }
    private void tbTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTrabajadorMouseClicked
        int seleccion=tbTrabajador.rowAtPoint(evt.getPoint());
        txtIdTrabajador.setText(tbTrabajador.getValueAt(seleccion, 0) + "");
        txtNombre.setText(tbTrabajador.getValueAt(seleccion, 1) + "");
        txtPaterno.setText(tbTrabajador.getValueAt(seleccion, 2) + "");
        txtMaterno.setText(tbTrabajador.getValueAt(seleccion, 3) + "");
        txtIdPersona.setText(txtIdTrabajador.getText());
        validar();
    }//GEN-LAST:event_tbTrabajadorMouseClicked

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaternoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txtPaternoKeyReleased

    private void txtMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaternoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txtMaternoKeyReleased

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txtEdadKeyReleased

    private void calenderFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calenderFechaKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_calenderFechaKeyReleased

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtIdTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTrabajadorKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
       boolean numero=key>=48&&key<=57;
       if(!numero){
           evt.consume();
       }
       if(txtIdTrabajador.getText().trim().length()==10){
           evt.consume();
       }
    }//GEN-LAST:event_txtIdTrabajadorKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        if(txtNombre.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaternoKeyTyped
        // TODO add your handling code here:
        if(txtPaterno.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtPaternoKeyTyped

    private void txtMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaternoKeyTyped
        // TODO add your handling code here:
        if(txtMaterno.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtMaternoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        if(txtCedula.getText().length()>=8){
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
       boolean numero=key>=48&&key<=57;
       if(!numero){
           evt.consume();
       }
       if(txtIdTrabajador.getText().trim().length()==3){
           evt.consume();
       }
    }//GEN-LAST:event_txtEdadKeyTyped

    public void limpiar(){
        txtIdTrabajador.setText("");
        txtIdPersona.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtEdad.setText("");
        calenderFecha.setDate(null);
        groupGenero.clearSelection();
        groupTipoTrabajador.clearSelection();
        txtCedula.setText("");
        groupEstadoCivil.clearSelection();
        idMaxP();
        idMaxT();
        validar();
    }
    public void validar(){
        if(txtNombre.getText().isEmpty()){
            jlbNombre.setText("*Obligatorio");
        }else{
            jlbNombre.setText("");
        }
        if(txtPaterno.getText().isEmpty()){
            jlbPaterno.setText("*Obligatorio");
        }else{
            jlbPaterno.setText("");
        }
        if(txtMaterno.getText().isEmpty()){
            jlbMaternoo.setText("*Obligatorio");
        }else{
            jlbMaternoo.setText("");
        }
        if(txtEdad.getText().isEmpty()){
            jlbEdad.setText("*Obligatorio");
        }else{
            jlbEdad.setText("");
        }
        if(calenderFecha.getDate()==null){
            jlbFecha.setText("*Obligatorio");
        }else{
            jlbFecha.setText("");
        }
        if(rdMasculino.isSelected() || rdFemenino.isSelected()){
            jlbGenero.setText("");
        }else{
            jlbGenero.setText("*Obligatorio");
        }
        if(rdDocente.isSelected() || rdAdministrativo.isSelected()){
            jlbTipo.setText("");
        }else{
            jlbTipo.setText("*Obligatorio");
        }
        if(txtCedula.getText().isEmpty()){
            jlbCedula.setText("*Obligatorio");
        }else{
            jlbCedula.setText("");
        }
        if(rdsoltero.isSelected() || rdCasado.isSelected()){
            jlbEstado.setText("");
        }else{
            jlbEstado.setText("*Obligatorio");
        }
        if(txtIdTrabajador.getText().isEmpty() || txtNombre.getText().isEmpty() || txtPaterno.getText().isEmpty() || 
                txtEdad.getText().isEmpty() || calenderFecha.getDate()==null || !(rdMasculino.isSelected() || rdFemenino.isSelected()) ||
                !(rdDocente.isSelected() || rdAdministrativo.isSelected()) || txtCedula.getText().isEmpty() || 
                !(rdsoltero.isSelected() || rdCasado.isSelected())){
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }else{
            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador_Per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador_Per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador_Per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador_Per.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrabajador_Per().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FECHA;
    private javax.swing.JLabel HORA;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser calenderFecha;
    private javax.swing.ButtonGroup groupEstadoCivil;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.ButtonGroup groupTipoTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCedula;
    private javax.swing.JLabel jlbEdad;
    private javax.swing.JLabel jlbEstado;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbGenero;
    private javax.swing.JLabel jlbMFecha;
    private javax.swing.JLabel jlbMHora;
    private javax.swing.JLabel jlbMaternoo;
    private javax.swing.JLabel jlbMensaje;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbPaterno;
    private javax.swing.JLabel jlbTipo;
    private javax.swing.JRadioButton rdAdministrativo;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdDocente;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdsoltero;
    private javax.swing.JTable tbTrabajador;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdPersona;
    private javax.swing.JTextField txtIdTrabajador;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
